---
volumes:
  passbolt-db:
  passbolt-gpg:
  passbolt-jwt:

networks:
  public-traefik:
    external: true
  passbolt-network:

services:
  passbolt-db:
    container_name: passbolt-db
    image: docker.io/library/mariadb:11.3
    env_file:
      - ./.env.db
    volumes:
      - passbolt-db:/var/lib/mysql
    networks:
      - passbolt-network
    restart: unless-stopped

  passbolt:
    container_name: passbolt-app
    image: docker.io/passbolt/passbolt:4.9.1-1-ce
    depends_on:
      - passbolt-db
    env_file:
      - ./.env.passbolt
    volumes:
      - passbolt-gpg:/etc/passbolt/gpg
      - passbolt-jwt:/etc/passbolt/jwt
    networks:
      - passbolt-network
      - public-traefik
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "passbolt-db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    labels:
      traefik.enable: "true"
      traefik.docker.network: "public-traefik"
      traefik.http.routers.passbolt-http.entrypoints: "web"
      traefik.http.routers.passbolt-http.rule: "Host(`passbolt.liuf.uk`)"
      traefik.http.routers.passbolt-http.middlewares: "SslHeader@file"
      traefik.http.routers.passbolt-https.tls: "true"
      traefik.http.routers.passbolt-https.tls.certresolver: "production"
      traefik.http.routers.passbolt-https.entrypoints: "websecure"
      traefik.http.routers.passbolt-https.rule: "Host(`passbolt.liuf.uk`)"
      traefik.http.routers.passbolt-https.middlewares: "SslHeader@file"
    restart: unless-stopped
