---
networks:
  public-traefik:
    external: true
  passbolt-network:

services:
  db:
    image: docker.io/library/mariadb:11.3
    env_file:
      - ./.env.db
    volumes:
      - /mnt/palette/nar-eksisi/docker/passbolt/db/:/var/lib/mysql
    networks:
      - passbolt-network
    restart: unless-stopped

  app:
    image: docker.io/passbolt/passbolt:5.5.2-1-ce
    depends_on:
      - db
    env_file:
      - ./.env.passbolt
    volumes:
      - /mnt/palette/nar-eksisi/docker/passbolt/app/gpg:/etc/passbolt/gpg
      - /mnt/palette/nar-eksisi/docker/passbolt/app/jwt:/etc/passbolt/jwt
    networks:
      - public-traefik
      - passbolt-network
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    labels:
      traefik.enable: "true"
      traefik.docker.network: "public-traefik"
      traefik.http.routers.passbolt-http.entrypoints: "web"
      traefik.http.routers.passbolt-http.rule: "Host(`passbolt.liuf.uk`)"
      traefik.http.routers.passbolt-http.middlewares: "SslHeader@file"
      traefik.http.routers.passbolt-https.tls: "true"
      traefik.http.routers.passbolt-https.tls.certresolver: "production"
      traefik.http.routers.passbolt-https.entrypoints: "websecure"
      traefik.http.routers.passbolt-https.rule: "Host(`passbolt.liuf.uk`)"
      traefik.http.routers.passbolt-https.middlewares: "SslHeader@file"
    restart: unless-stopped
